
runtime: nodejs16


handlers:
    # Serve all static files with urls ending with a file extension
    - url: /(.*\..+)$
      static_files: dist/client/\1
      upload: dist/(.*\..+)$
      # catch all handler to index.html
    - url: /.*
      static_files: dist/client/index.html
      upload: dist/client/index.html

env_variables:
   FIREBASE_SERVICE_KEY: <FIREBASE_SERVICE_KEY>
