# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@typescript-eslint/*"
    groups:
      client-eslint-prettier:
        applies-to: version-updates
        patterns:
          - "eslint*|prettier*"
        update-types:
          - "minor"
          - "patch"
      client-types:
        applies-to: version-updates
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
      tailwindcss:
        applies-to: version-updates
        patterns:
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@typescript-eslint/*"
    groups:
      server-eslint-prettier:
        applies-to: version-updates
        patterns:
          - "eslint*|prettier*"
        update-types:
          - "minor"
          - "patch"
      server-types:
        applies-to: version-updates
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      nestjs:
        applies-to: version-updates
        patterns:
          - "@nestjs*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
