
runtime: nodejs16
service: server-service

env_variables:
   API_KEY: <API_KEY>
   DOMAIN: <DOMAIN>
   URL_CLIENT: <URL_CLIENT>
   GENERIC_EMAIL: <GENERIC_EMAIL>
   GCLOUD_PROJECT_ID: <GCLOUD_PROJECT_ID>
   NODE_ENV: <NODE_ENV>
